spring:
    profiles:
        include: db,baidu,mybatis
        active: dev
    application:
         name: image-recognition
    cloud:
        config:
            label: master
            profile: dev
            uri: http://localhost:8769
            fail-fast: true
    mvc:
        view:
            prefix: /view/
            suffix: .jsp
        static-path-pattern: /static/**

    resources:
        static-locations: classpath:/static/,classpath:/public,classpath:/resources,classpath:/META-INF/resources,servlet context:/,classpath:/view/

    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 1000MB

    #页面热部署
    thymeleaf:
        prefix: /
        suffix: .html

server:
    port: 8082
    servlet:
        jsp:
            init-parameters:
                development: true

#management.endpoints.web.exposure.include: *


---
# 配置spring的时区
spring:
    jackson:
        time-zone: GMT+8

---
spring:
    devtools:
        restart:
            enabled: true  #设置开启热部署
            additional-paths: src/main/java #重启目录
            exclude: ../../webapp/WEB-INF
    freemarker:
        cache: false    #页面不加载缓存，修改即时生效

---
logging:
    levels: info
#    file:
#        path: