server:
    port: 8761

spring:
    application:
        name: eureka-server

eureka:
    instance:
        hostname: 192.168.163.1
    client:
        register-with-eureka: false
        fetch-registry: false
        service-url:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


